In [1]:
import pandas as pd

In [3]:
known_ADs = pd.read_csv("../output/known_ADs_considering_isoforms.csv")
known_ADs["length"] = known_ADs["ProteinRegionSeq"].str.len()
known_ADs[known_ADs["length"] > 150]

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes,length
2,AHCTF1,1445,1698,Q8WYP5,"[['Q8WYP5'], ['Q8WYP5']]",nan / nan,Q8WYP5 / Q8WYP5,"PMID: 11952839, Soto / transcriptionalactivity...",TF,IRANDNKSMADVLGDGGNSSLTISEGPIVSERRLNQEVALNLKEDH...,NaN,254
5,AHR,532,848,P35869,"[['P35869'], ['P35869'], ['P35869']]",ENST00000242057 / nan / ENST00000242057,P35869 / P35869 / P35869,"DelRosso et al. / PMID: 8794892, Soto / DelRos...",TF,QDSKNSDLYSIMKNLGIDFEDIRHMQNEKFFRNDFSGEVDFRDIDL...,NaN,317
6,AIRE,292,545,O43918,[['O43918']],NaN,O43918,"PMID: 11274163, Soto",TF,HQKNEDECAVCRDGGELICCDGCPRAFHLACLSPPLREIPSGTWRC...,NaN,254
8,AKAP8L,1,384,Q9ULX6,"[['Q9ULX6'], ['Q9ULX6'], ['Q9ULX6']]",nan / nan / ENST00000397410,Q9ULX6 / Q9ULX6 / Q9ULX6,"PMID: 11402034, Soto / activation_regions.txt,...",TF,MSYTGFVQGSETTLQSTYSDTSAQPTCDYGYGTWNSGTNRGYEGYG...,NaN,384
16,AR,652,910,P10275,[['P10275']],NaN,P10275,"PMID: 9033395, Soto",TF,PTEETTQKLTVSHIEGYECQPIFLNVLEAIEPGVVCAGHDNNQPDS...,NaN,259
...,...,...,...,...,...,...,...,...,...,...,...,...
724,ZFX,1,335,P17010,[['P17010']],NaN,P17010,"PMID: 2105457, Soto",TF,MDEDGLELQQEPNSFFDATGADGTHMDGDQIVVEVQETVFVSDVVD...,NaN,335
725,ZFY,1,333,P08048,[['P08048']],NaN,P08048,"PMID: 2105457, Soto",TF,MDEDEFELQPQEPNSFFDGIGADATHMDGDQIVVEIQEAVFVSNIV...,NaN,333
727,ZIC2,100,255,O95409,[['O95409']],NaN,O95409,"activation_regions.txt, GSL",TF,PHAAHVGSYSGPPFNSTRDFLFRSRGFGDSAPGGGQHGLFGPGAGG...,NaN,156
738,ZNF148,444,794,Q9UQR1,[['Q9UQR1']],NaN,Q9UQR1,"PMID: 9417107, Soto",TF,IDQVDNLQEGPSKPVHSSTNYDDAMQFLKKKRYLQAASNNSREYAL...,NaN,351
747,ZNF516,1,431,Q92618,[['Q92618']],NaN,Q92618,"activation_regions.txt, GSL",TF,MDRNREAEMELRRGPSPTRAGRGHEVDGDKATCHTCCICGKSFPFQ...,NaN,431

In [ ]:
known_ADs[known_ADs["length"] < 50]

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes,length
3,AHR,118,126,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,LLQALNGFV,NaN,9
4,AHR,266,268,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,FAI,NaN,3
22,ARNTL,582,626,O00327,[['O00327']],NaN,O00327,"PMID: 10971655, Soto",TF,DMIDNDQGSSSPSNDEAAMAVIMSLLEADAGLGGPVDFSDLPWPL,NaN,45
30,ATF3,1,40,P18847,"[['P18847', 'P18847-2', 'P18847-3']]",NaN,P18847,"PMID: 22347845, 12881527, 1406655, Soto",TF,MMLQHPGQVSASEVSASAIVPCLSPPGSLVFEDFANLTPF,NaN,40
45,BSX,194,233,Q3C1V8,[['Q3C1V8']],NaN,Q3C1V8,"PMID: 17353277, Soto",TF,AATAAEARLSLPAGPFVLTEPEDEVDIGDEGELGSGPHVL,NaN,40
...,...,...,...,...,...,...,...,...,...,...,...,...
733,ZN644,852,893,Q9H582,"[['Q9H582', 'Q9H582-2']]",NaN,Q9H582,Staller Activity Data,TF,SYETEDESSWDNVELGDYTTQAIEDETYSDINQEHVNLFPLF,NaN,42
734,ZN654,680,724,Q8IZM8,[['Q8IZM8']],NaN,Q8IZM8,Staller Activity Data,TF,GSPNNSLNNVFKPLTECGDDYEEEEDEEGDYEEDDYDLNQETSVI,NaN,45
735,ZN777,454,495,Q9ULD5,[['Q9ULD5']],NaN,Q9ULD5,Staller Activity Data,TF,EEQDEEEEEEEEDELPQHLQSLGQLSGRYEASMYQTPLPGEM,NaN,42
736,ZNF143,178,195,P52747,[['P52747']],NaN,P52747,"PMID: 9566884, Soto",TF,PDTISALEQYAAKVSIDG,NaN,18
758,c-Jun/AP-1,238,257,P05412,[['P05412']],NaN,P05412,"Choi 2000 list, GSL",TF,ETPPLSPIDMESQERIKAER,NaN,20

In [4]:
known_ADs

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes,length
0,ABRAXAS1,121,200,Q6UWZ7,[['Q6UWZ7']],ENST00000321945,Q6UWZ7,DelRosso et al.,CR,LQEHFSNQDLVFLLLTPSIITESCSTHRLEHSLYKPQKGLFHRVPL...,NaN,80
1,AEBP1,1088,1158,Q8IUX7,[['Q8IUX7']],NaN,Q8IUX7,Staller Activity Data,TF,EVVTEFGTEVEPEFGTKVEPEFETQLEPEFETQLEPEFEEEEEEEK...,NaN,71
2,AHCTF1,1445,1698,Q8WYP5,"[['Q8WYP5'], ['Q8WYP5']]",nan / nan,Q8WYP5 / Q8WYP5,"PMID: 11952839, Soto / transcriptionalactivity...",TF,IRANDNKSMADVLGDGGNSSLTISEGPIVSERRLNQEVALNLKEDH...,NaN,254
3,AHR,118,126,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,LLQALNGFV,NaN,9
4,AHR,266,268,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,FAI,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...
755,ZXDB,576,703,P98169,[['P98169']],NaN,P98169 / P98169,"R4TA_regions.txt / activation_regions.txt, GSL",TF,QDLLAQLEAANSLTPSSELTSQRQNDLSDAEIVSLFSDVPDSTSAA...,NaN,128
756,ZXDC,579,688,Q2QGD7,"[['Q2QGD7', 'Q2QGD7-2'], ['Q2QGD7', 'Q2QGD7-2']]",nan / nan,Q2QGD7 / Q2QGD7 / Q2QGD7,"PMID: 16600381, Soto / R4TA_regions.txt / acti...",TF,DSPLVLGTAATVLQQGSFSVDDVQTVSAGALGCLVALPMKNLSDDP...,NaN,110
757,c-ETS1,175,286,P14921-3,[['P14921-3']],NaN,P14921,"Choi 2000 list, GSL",TF,ILQKEDVKPYQVNGVNPAYPESRYTSDYFISYGIEHAQCVPPSEFS...,NaN,112
758,c-Jun/AP-1,238,257,P05412,[['P05412']],NaN,P05412,"Choi 2000 list, GSL",TF,ETPPLSPIDMESQERIKAER,NaN,20
759,c-Myb / MYB / MYB,232,361,P10242,"[['P10242', 'P10242-10', 'P10242-4', 'P10242-5...",ENST00000367814 / nan / nan,P10242 / P10242 / P10242 / P10242 / P10242,"DelRosso et al. / PMID: 9418897, Soto / nan / ...",TF,LPATGQPTVNNDYSYYHISEAQNVSSHVPYPVALHVNIVNVPQPAA...,NaN,130