In [26]:
import protfasta

In [ ]:
plant_TF_dict = protfasta.read_fasta("../data/PlantTFDB-all_TF_pep.fas", invalid_sequence_action='remove')
plant_TF_dict

{'KFK36254.1 Arabis alpina|G2-like|G2-like family protein': 'MYSAIRSLPVDGSMGEYSDGTNLPIEACLVLTTDPKPRLRWTTELHDRFVDAVTQLGGPDKATPKTIMRTMGVKGLTLYHLKSHLQKFRLGRLPCKESTDNSKDVSSVAESQDTGSSTTSSLRLAAQEQKESYQVTEALRAQMEVQRRLHEQLEVQQRLQLRIEAQGKYLQTILEKACKAIEEQAVAFAGLEAAREELSELAIKVSNGCQSTFDTTKMTIPSLSELAVAIEHKNNCSAESSLTSSTVGSPVSAAMMKKRHRGVFGNGDSVVVGHEAGWVMPSSSIG',
 'KFK25038.1 Arabis alpina|GeBP|GeBP family protein': 'MAPKHTDTIQNPPMPSSSSEEESASSGEDSDSSKKHNSASDSDPIKTKIVVTKPESSGSMKTTTKSSVVVAEPESTTAKRPLKETEEDVEVKKKKMKTELVMKNQEPEEKVSGDETKKQLMFQRLFSENDEIALLQGILDFTSTRGDPYEKMDVFCEYVKKLINFDANKSQLVTKIRRLKKKFGNTIKNSLKKGKSEDEIVFSKDLDQKAFHLSRKVWGSNGVLASKSRKKLGENSKEIIKKEEKPKQNVVSVCRSSSEGGEIASFFKAENTTAFGLDEPTVAARWEMVSDVAKKREMEEKLKKLKATQEELCLQRTGIVADTVKLIFNDNASSSSK',
 'KFK35037.1 Arabis alpina|bZIP|bZIP family protein': 'MTTTTTPHWPDFSSQKLPSIAATAAATAATAGQNQQNQNPSWMDEFLDFSATRRGTHRRSISDSIAFLEAPSSGVGNHHHHFDRFDDEQFMSMFNDDVHQNHNNHNNNHHHHHHNVGHTRSSSNTSTPSDHNSLSDEDNNNNKEPLPSDHDHHMENNNVDNDKNNVAGNNYNESDEVQSQCKTEPQDGPSSANQNSGGSSGNRIHDPKRVKRILANRQSAQRSRVRKLQYISELERSVTSLQTEVSVLSPRVAFLDHQRLLLNVDNSAIKQRIAALAQDKIFKDAHQEALKREIERLRQVYHQQSLKKMENSNVSDQSPVDIKPSVEKEQLLNA',
 'KFK44643.1 Arabis alpina|ERF|ERF family protein': 'MEGERHDSTTSSSRKRSHEPAEERPASHVATMAFKEKPYRGIRMRKWGKWVAEIREPNKRSRLWLGSYTTAVAAARAYDTAVFYLRGPSARLNFPDLLVQEGDRRSAAAADMPAALIREKAAEVGARVDALLASADPAAHSSSLPVLVEKPDLNKIPESGDI',
 'KFK32619.1 Arabis alpina|B3|B3 family protein': 'MAKPPQFFHTLVNTHLVIPKDFFSKYIQGKSVDDTVELKSDSTDINWKVKMIGRRLNDGWEEFAVANRLQIGDVLLVRYEDDLVLHVSNLGPNCSETRDNNNDDQNNIGKLLLKKRMYPKAELDDDDDGDMELPIKKKVKKSLYTEVSCDVENIKVESIEDECSSMEIESSEDEYRLMESLLEIEKTKHTIDREQEDKERESPFIDSSNRDKIKRDESNKEESRSRERNKNYMTLTITPYCIRKSRMRLPPCFTKENAINKPGMITLLGKDGLKQQANLLLDNARGTMSLGSGWNSFVEKNDLKIGDSFTFKLIWEDTTPVLRLCDAESPFKTNKKTSPFKTNKKESPFIDSSNRDKINRDEITKEERNKNYLRAKDTTLPSENQLVTLTITPYRFRKGRLPLPAWFTKDNGINKPGMITLLGKDGIKHPTKLLLDKVNAVMALGGGWKPFVEENGLKTGDSFTLKLIWEDKTPVLSLCPAERSIDKVGGGCSETNQKNSLPVEPSSCKKISNDENSKDEYKPIERENTHLRGRDSTPSCQKQFVTLKVTPSCFTNCRLILPTEFAKENSMNKPGVIYLVGKD',
 'KFK39227.1 Arabis alpina|B3|B3 family protein': 'MPRPFFHKLIFSSTIQEKRLRVPDKFVSKFKDELSVAVALTVPDGHVWRVGLRKAENKIWFHDGWQEFVDRYSIRIGYLLIFRYEGNSAFSVYIFNLSHSEINYHSTGLMDSAHNHFKRARLFEDLEDEDAEVIYPSSVYPSTLPDSTAPANKGYAGTAIQSLFTGPVKDEEATPTPKVPKKRGRKKKNADPEEINSSAPRDDDPENRSKFYESASARKRTVTAVERDRAINASKTFEPTNPFFRVVLRPSYLYRGCIMYLPSGFAEKYLSGISGFIKVQLAEKQWPVRCLYKAGRAKFSQGWYEFTLENNLGEGDVCVFELLRTRDFVLKVTAFRVNE',
 'KFK37976.1 Arabis alpina|NF-YA|NF-YA family protein': 'MAMQTVREGVLSAPQISWWNAFGSQPLAPENSDSFAGVKVGSAGETTEHGVDKQSNSVSHLAFSLGDAKSSRVVPKTHGVAFSLQSPCLELGFTQPPMYTKYPCVEQQYYGVVSAYGSQGRVMLPLNMETEDGPIYVNSKQYHGIIRRRQSRAKAAAVLEQNKLSSSRCRKPYMHHSRHLHALRRPRGSGGRFLNTKSQNMEKSGTNAKKDDETKQPQPQQSNSQNSEVLHPENGTINLSNGLNVSGSEVTSMNYFLNTPVHSLGGMVMPSKWIAAMDNGCCSFKT',
 'KFK41782.1 Arabis alpina|MYB|MYB family protein': 'MCSRGHWRPAEDEKLKDLVEQYGPHNWNAIALKLPGRSGKSCRLRWFNQLDPRINRNPFTEEEEERLLAAHRIHGNRWSIIARLFPGRTDNAVKNHWHVIMARRTRQTSKPDHRLIPSTTSSSSFMASEQMMMSCGDRKRILPADVISNYPYQFSHINHLQFLKEFFTGKIALNAKANQSKKPMEFYNFLQVNTDSNKSEIIDQDSDQSNLKDLDNKNESRVPFFDFLSVGKSAS',
 'KFK27808.1 Arabis alpina|bZIP|bZIP family protein': 'MQEQATSSLAASSLPSSSERSSSSAPPLEIKEGMESDEEIRRVPEFGGEITGIVNSGQEQGQATVGERQRKRGRNVADKENKRLKRLLRNRVSAQQARERKKVYLTDLEKKVKELENKNSQLEERLSTLQNENQMLRQILKNTTANKRGGGSGGGSNPEC',
 'KFK37037.1 Arabis alpina|C2H2|C2H2 family protein': 'MDETSGRRETHDFMNVNVESFSQLPFIRRTPPVKEKSSIIRLFGQELVGDNSSSGTLQQQQQEDMSVDSSEIITTTTKQEESSENVKEKDKDKDNNNNRRFECHYCFRNFPTSQALGGHQNAHKRERQHAKRGSMTSYLHHHHPDSHHNVYGFLNNHRHYPTWTSEPRYYGGVGGGQHQTASYYSRTLPPPSNSPTIIGSPLGMWRVPPSTSSNAIQGVYSASSTFRTHEQEIKEPNWPYNRLMKPNNVQDHVSLDLHL',
 'KFK23649.1 Arabis alpina|GeBP|GeBP family protein': 'MTKKTLNPLDDPPTASSSDDDEVHTSAGEEEEEEEEEDSSSEEAPSAAVTVAVPGKTTVTKQGSDSDSGSETETDSDSETGSGKSMAVTVVATNPKKKEATLALPAMKSGTKRPSEGTSRDGGGNAKKKNKIGEDIKKPAFQRLWSEEDEIALLQGMIDFRDDTGKIPYEDTNGFYDYMKKSISVEVSKSQFMDKIRSLKKKYTGKGKNGKDVSFTKPHDVKSFGLSKFIWGPDGMGIESAKSNGISKKSKSKKLESVKQDLFLGNGKMVEEVDDDDDDGKKVVVETGKTTDWFENSFLVGSIASFGVDEYTVKQRWREAPVEDKKKIEEKMKALRAKEIEYVLEKTKFLNDFASMIAEASK',
 'KFK33519.1 Arabis alpina|G2-like|G2-like family protein': 'MLLKSFGDNFQSDQTTQKLEDLLSLLEQERLKIDAFKRELPLCMQLLNNAVEVYKQQLEAYRANSNNNQSLATRPVLEEFIPLRNQPEKANNKGSNWMTTAQLWSQPEIKPKNIDSATDHSLPKDEIASSPKLGHFDAKQRNGGGAFLPFSKEQSLPELALSTEVKRVSLTNEHTNDHDGNDENMINNGNNNNNNNNNSNSNGVSSTTSQSNRKARRCWSPDLHRRFVQALQMLGGSQATPKQIRELMKVDGLTNDEVKSHLQKYRLHTRRPSPSPQTSGGPGPHLVVLGGIWVPPEYTTGHGGTPTLYHHQVHHHHGTAAAQPPPHFCSSQEFYTTPPQPLHHNNHFQTFNGSSGGGAASTDSGHQLTDGATDEGKSPESGGGERKGLAALREEGENQSNINGSEITLKF',
 'KFK45149.1 Arabis alpina|MYB|MYB family protein': 'MGRSPCCDENGLKKGPWTPEEDQKLIDYIHKHGHGSWRALPKLADLNRCGKSCRLRWTNYLRPDIKRGKFSTEEEQTILHLHSILGNKWSAIATHLQGHHNPNDAPPSLPADASSSSSYGGGDGASLYWPDFCFDENIINDIS',
 'KFK31606.1 Arabis alpina|MYB|MYB family protein': 'MGKRTSSGVKREELNRGAWTDHEDKILRDHIMTHGEGKWSTLPNEAGLKRCGKSCRLRWKNYLRPGIKRGNISSDEEELIIRLHNLLGNRWSLIAGRLPGRTDNEIKNHWNSNLRKRIPKTQTNQPKHRKYSTNKNRNNVGVIRTKAIRCSKAISTTLLPPKEPENTLIDQAGSSLLGDLEIDFDRIQTESFLFPELMDFDTLGCGNVTPLVSSDEILGDLVRTDEDWKRNLDLNRPFTSYHHHDEDWLRDFSC',
 'KFK30311.1 Arabis alpina|ERF|ERF family protein': 'METSTEVVSTQVVTTATTVTRKREKPYKGIRMRKWGKWVAEIREPNKRSRIWLGSYSTPEAAARAYDTAVFYLRGPSARLNFPELLAGITVTRGGDCDMSAAYIRRKAAEVGAQVDALETAGGHHRHQHQQQHHQGSLFSTGKWSNRI',
 'KFK26065.1 Arabis alpina|NAC|NAC family protein': 'MAVVVEEDVVLNHGGEELVDLPPGFRFHPTDEEIITHYLKEKVLDSRFSAVAMGEADLNKCEPWDLPKRAKMGEKEFYFFCQRDRKYPTGMRTNRATESGYWKATGKDKEIFKGKDCLVGMKKTLVFYRGRAPRGEKTNWVMHEYRLEGKYSYHNLPKSARDEWVVCRVFHKNNPSTTTQLMTRIPNEDLPRMDSLENIDHLLDFSSLPPLIDPSFMGQAEQASFKPINPSTYNNISSPFQTHHFNSYQSIFNQGFGSASGSGSTYNNNNNNDMIKTEQSLVSVSQETCLSSDVNAATTTEVTSGPVMKQEMRMMGMGMVNGSKSYDDLCDLRGILWD',
 'KFK41311.1 Arabis alpina|RAV|RAV family protein': 'MVSSCIDEISSTSESFPTAKKFSPPPPPPAALRLYRMGSDGSSVVLDSENCVETESRKLPSSKYKGVVPQPNGRWGAQIYEKHQRVWLGTFNEEEEAAHSYDIAARKFRGRDAVVNFKTTLDDDVLAFLEAHSKAEIVDMLRKHTYADELDQSNKRRILSVDVNGKPKVTSQNDSVSRTREVLFEKAVTPSDVGKLNRLVIPKQHAEKHFPLPLSPSPSVTKGVLINFEDVTGKVWRFRYSYWNSSQSYVLTKGWSRFVKEKNLRAGDVVTFERSTGPDRQLYIDWKIRSGPSNNPVQVVVRLFGVDIFNAKPNDVVAVCGGKRSRDVDMFALRCSKKQAIINAL',
 'KFK30743.1 Arabis alpina|NAC|NAC family protein': 'MAILRIPRSQIPGSRFNPTELELINYLRRRIDRNKKSRYITDLNVYEKEPWLLQHVIHPKFKKNVWFYFVTRKRPAKIKNPNSKRTSRVVGSCRWKTTGLLTDLRDEDGVKVGTMQSIVFKAKIEGKKDEINTGWVMHEFLLDKTGFQEVVLCRIEFKHENKNALYAPRLEPIVIGEADLVENKEKKEEDFLSLTDLESLGISMDLPKHPMSFQEPWFGPCSSETVPNLTAMGQESSYLVNGGIEQHQDFGYCSYQQQNQTLGHFSSMEPQQSYGQGFGGVAHAYQNQYLGQGTNPWQVSMMNQDMAIMTRGMMVHQQEQCLAAQYQQLSMNRGMEQHQDFGSCGQFVGESLGQQQNQFLGQQVTNLSPLGQQQWNVYSGPYLAQPYDQGIVPVTHQDLNSSYLCLAQDLGQNNDLSVVPMETQQAGMEPQQHDSSCFNHNVVEDLATQRQHLGQESNLSLTQQQNQILGHLSPMEQQQNMNQALEEQHYGQVVPESAQLDLGQTIDLPKETQQQDNVVENLPTQLHLETNQETVLPINQGINEPHGDHCSSSTLNESNQQSFDDETALTDQELDSMMDNLRNEEWAKKLGVNTPEEEAELTASLRNCNTYQSLLNYFCPI',
 'KFK43201.1 Arabis alpina|NF-YC|NF-YC family protein': 'MDQQEHGQSGYGSNPYQTNPMTTTVAGSVGAAAPPGQLAFHQIHQQQQQQQLAQQLQVFWENQFKEIEKTTDFKNHSLPLARIKKIMKADEDVRMISAEAPVVFARACEMFILELTLRSWNHTEENKRRTLQKNDIAAAVTRTDIFDFLVDIVPREDLRDEVLGSIPRGAVPEAAAAGYPYGYLPAGTPPLGNPGMVMGNPGGAYPPNPYMGQPMWQQPGPDQPDSEN',
 'KFK42926.1 Arabis alpina|NAC|NAC family protein': 'MENMGDSSIGPGHPHLPPGFRFHPTDEELVVHYLKKKAASIQLPVSIIAEIDLYKFDPWELPSKASFGEHEWYFFSPRDRKYPNGVRPNRAATSGYWKATGTDKPIFTCNSHKVGVKKALVFYGGKPPKGIKTDWIMHEYRLTDGNLSTTAKPPDPVTTRKNSLRLDDWVLCRIYKKNSSQRPTMERILLREDLMEGMLSKSSANSSSTSVLDNNDNNNNNNNEEHFFDGMVVSSDKRSLCGQYRMGHEASGSSSFGSFLSSKRFHHTSDLNNDNYNVSFVSMLSEIPQSSGFHGNGAIDTTSSLADHGVLRQAFQLPTMNWHS',
 'KFK41622.1 Arabis alpina|C2H2|C2H2 family protein': 'MGEESNIDMDASLIKDIRKYLCQYCGISRSKKYLITSHILSHHKMEMEEERDDEACEVEEEALGKHNCQECGAEFKKPAHLKQHMLSHSIERPFTCYVDDCAASYRRKDHLNRHLLTHKGKLFKCPMENCKSEFSVQGNVGRHIKEMHKNGDGSKDDIGNGDSHPTEGSIGQKPHVCQEVGCGKAFRYPSQLQKHQDSHVKLDSVEAFCSEPGCMKYFTNDECLKAHIRSCHQHVNCEICGSKHLKKNIKRHLRTHDEDSAPGVFKCEVEGCSSTFSKPSNLQKHMKAVHEDIRPFICGFPGCGMRFAYKHVRNNHENSGSHVYTCGDFVATDENFTSRPRGGLKRKQVTAEMLIRKRVMPPQFESQEEHKTC',
 'KFK32306.1 Arabis alpina|ARF|ARF family protein': 'MEQEKSLDPQLWHACAGSMVQIPSVNSTVFYFAQGHTEHAHAPPDFHAPRVPPLILCRVVAVKFLADAETDEVFSKITLLPHNELDLGNDAVLCDANGNEKPASFAKTLTQSDANNGGGFSVPRYCAETIFPRLDYTAEPPVQTVIAKDIHGETWKFRHIYRGTPRRHLLTTGWSTFVNQKKLIAGDSIVFLRSESGDLCVGIRRAKRGSGDDETTTSKLMLMKRENAAAGRVKVEAVAEAVARAACGQAFEVVYYPRASTPEFCVKAADVRSAMKIRWCSGMRFKMAFETEDSSRISWFMGTVSAVHVADPIRWPNSPWRLLQVAWDEPDLLQNVKRVSPWLVELVSNMPAMHLSPFSPRKKLRIPQPFDDGTKFPIFSPGFTHNGDSMCYLSKDNISSSNNNNAPAGIQGARQAQQLFGSPSPSLLSDLNLTSYSSNKLQSPAMFLSRHHYDNILSRQARDTETNNNISCSLTIGNPALVQDHKKSGSVKTHQFLLFGQPILTEQQVMNRKRSLEAEAQDDNSSAARGLTWNYGLQGLETGHCKVFMESEDVGRTLDLSVIGSYQELYRKLAEMFCIQERSDLLTHVVYRDANGVIKRIGDEPFSDFMRATKRLTIKMDIGGDNVRKTWITGIRNGENGIDASAKTGPLSIFA',
 'KFK31038.1 Arabis alpina|WRKY|WRKY family protein': 'MGEEEEEVYEWTRGFGDDYVDELLVNEPPLFFMPQEPPNEDAIKNKFLSSTLYSGPTIQDISNALTRTLPVPQVSISTVPTSEMSTLSRMDKYTLKVKNNCNGMSDDGYKWRKYGQKSIKNSPHPRSYYKCTNPICNAKKQVEKSIDEPNTYIITYEG',
 'KFK38258.1 Arabis alpina|MYB|MYB family protein': 'MMMRKLDSPTIRDKNKPNLACGGNNNKPKLRKGLWSPDEDEKLIRYMLTNGQGCWSDIARNAGLLRCGKSCRLRWINYLRPDLKRGSFSPQEEDLIFHLHSLLGNRWSQIATRLPGRTDNEIKNFWNSTLKKRLKNNSSNNNNNTSSGSSPNNSNSNSLEPRDQHVEMGGKSNPMMDGYHHHDDMMIVGNNIHMDSSSFNFAPMVSSMGLNQLDPLISVPDHNRYHQMGNTGNVFNVNGLGDYGNATLDPISKCVSVEGEWFNLPPSENNNVIACNTSNNLNLAALDPCFNSKNLCQVGNVLGMENGSWEIENPKIGDWDLDGLIDNNSSFPFLDFQVD',
 'KFK37155.1 Arabis alpina|bHLH|bHLH family protein': 'MYPSSSNKSTAQDGGGDSHNNPYDSAAGTTRDFSSLGSQTNHNSPSHPPPPTRRQNNPNVVGHYISGDPSSFGPDSGASSSLFRHRSSPAGFFDQHLPTTDPHGRPNGGYGGGGGGGERGPSRLKSEARFSGGSSSNSHQEHNSLPRISEAEAGATAINGVASTSMSFGNVHNNWDNSSSHISFTIDEPGKRSKTTDFFTLETQFSMPQTSLEMARMENMMNIPEDSVACKVRAKRGFATHPRSIAERERRTRISGKLKKLQELVPNMDKQTSYADMLDLAVEHIKVTGKGNGEMHMWSMQEAMMKRYDMFPNTMQESIEGKKDQGIKLEEKKIHSKNFNYM',
 'KFK40029.1 Arabis alpina|B3|B3 family protein': 'MALLLLFVNRAIPHDLVKTLSENDLSRKMKIKTEWGRSWKVEISKNPRFYFMEKAGWETFVRENFLGDSELLTFIHKGKMRFTLIIYNKDGKEMLQPRQAAPFLASSSRIKTEDVKKEEVVVSSELSSLDPVTPAAESNGRRKLNFGKMKAEESQSSKRAKTKFRDSAGASSSSATGFTISIKKSYLNFLAIPVSFAKDHMQEGRTMFKIHDSEMKKSWDVAYVKRNTNTVFSAGWIQLVKEYPLRLGNTCKFTVINPTELRLDVLKP',
 'KFK37625.1 Arabis alpina|NAC|NAC family protein': 'MARAWIVDGRGIATKVKNASVSSASQIKDCGAYVDCPRCSYRIDNSNVLAPWPGLPKGVKFEPADEDIIEFLEAKCGIGGSQPHVLIEEFIRPVTEDVGINYTHPKNLPGANKDGVSVFFFHKMVQAYGTGQRKRRKITPTCLDEEPVRWHKTGRTKAVFLNGIQRGCKKIMVLYKSARKGSKPEKSNWVLHQYHLGTEGEEIGDYVVSKVTYQQQKIVEVPDEGESSGVRSGPRTPKTNTPQPPRPVDSLAGDEEAFDDKLFDPFGEGLENIPEAVLEKMWSKKARMEEDYVVNLNEDNLTCNESIEASSVWENQTLLPNPNLGTIGEMDGFSITDLENADLGTPPDLLTLASQESLLNWFGWQ',
 'KFK36580.1 Arabis alpina|TCP|TCP family protein': 'MSTEMVFHKLHTTESNLNTITPESRSQTQIVKSATGGRITKDRHTKVYGRGRRVRMPALAAARIFQLTRELGHKSDGETIEWLLRKAESSIIAATGTGTVPSEPISSSVGSSPPEPLPVLFAPQTLTQLQTQTQTQTQQTLFSETPSCRLDLSQPIGVHYSVNGGGGYNHMPYTAMLFEPMNTTVESGGEITAEERRMKEVVENCRRHHN',
 'KFK35873.1 Arabis alpina|Trihelix|Trihelix family protein': 'MEDHQNHPQYGIPLPQPSPHFSSDLFGFNIVSGPDQHHRVQFTDHEMGFLPRGVQGLTVAGPNSNTVVASTSGGGGGFSGFTDGGETGRWPRQETLMLLEVRSRLDHKFKEANQKGPLWDEVS',
 'KFK35799.1 Arabis alpina|FAR1|FAR1 family protein': 'MERSESGDGDVEATSVYLQTEEIHEGDDDPMSLRIGEALVCSSDHEIDIGFSQRKTEEETRVFDDEQIGLLPLDSKEFDAPAIGMEFESYDDAYNYYNCYATEVGFRVRVKNSWFKRRSKEKYGAVLCCSSQGFKRINDVNRVRKETRTGCPAMIRMRQVDSKRWRVLEVMLDHNHLLGSTVYKSVKTKRKCVSSPVSDSKTIKLYRTHVMDTENNVNLNTTVKRQFQYSAGSPDTLSLRRGDSAAIYNYFCRMQLTNPNFFYLMDVNDEGRLRNVFWADGFSKVSCSYFGDVVFIDNTYISAKFEIPLVTLSGVNHHGKTTLLSCGLLAGETVESYHWLLKVWLSVMKCAPQTIVTDRCKPLEAAISQVFPRSNHRFSLTHIMRKIPEKLGGLHNYDGVRKAFTKAVYETLKVVEFEAAWGFMVHNYGVIDNEWLRTLYEDRARWAPVYLKDTYFAGIAAARPGETLNPFFERYIHKQTPLKEFLDKYELALQKKHKKETLSDIESLTLNNTELKTKCSFETQLSRIYTKDMFKKFQVEVEEMYSCFSTTQLHIDGPFVIFLVKERVQSESNRREIRDFEVLYNRSVGEVRCICSCFNFYGYLCRHALCVLNFNGVEELPMRYILPRWRKDYKRIHGVDNGSSGFVDGMDRVQWFDQLYKNALQVVEGGMVSLDHYKVAMQVLEQSLDTVFSVEEKHD',
 'KFK38438.1 Arabis alpina|NAC|NAC family protein': 'MGRGSSLAPGFRFHPTDEELVCYYLKRKICNKPLKFDAISVTDVYKSEPWDLPDKSKLKSRDLEWYFFSMLDKKYRNGLKTNRATENGYWKTTGKDREIRYGSRVVGMKKTLVYHKGRAPRGERTNWVMHEYRLVSEDTDKEKKTGVQQDSYVLCRIFQKSGTGPKNGENYGAPFVEEEWEEDDMVFVPGQDLGSEDCVYVDVDEFDQKLDNALVYDAVPIPLNFDYGESSNNAETNYSDSNKYMQPGNYVDSNIYFEQPAEFSEGGQKPIIGDGSLQNDALFPDEGNGCGVQDDSTANLQSSDNIFESDTSRYNEYPGESNYFTGEAFLDPNNSLLQNDGLFLETNDLGSTQQDGFDYEDYLTFFDEDDENLTFDPSQLIGTEDVIPDQEELFQKAETKELEKEEASGGKQVVEEKEKDEASCSKQVDAYATEFEPDYKYSFLKKASNMLGAIPAPPAFASEFPAKDASIQLHAAQSSGSVHVTAGMITISDSNTSWSYGKDGNGNLELILSFGLAQGNAASEKSGNSLTRAMFMFMCFWVLVLSISFKVSTLVSSR',
 'KFK34147.1 Arabis alpina|C3H|C3H family protein': 'MANTEEGISGSIADPASRSSDPSADRSLSDLNHVAEELSEEFKNVGLVQVNVFESNGGVDSTRVDGDGDSGWGESKSEKREVVYPVRPGAEDCSFYMRNGCCKFGSTCKFNHPPPKKIQIVRVNKVREKEEDVDEQGLLDCKYYFMTGGCKFGETCRFKHTKPKTFQSSVPELNFLGLPIRPGEIECPYYMRTGSCKYGADCKFNHPDPATVGGTDSPSYHGNNGGSIGSFSPKSTFQASSTSWSSPRHSNGTSPFIPTMLSQTHRVPSQTPEWNGYQVASVYSSERSVFKPSSTYFTNNSLAETNIFSPYQHQMPAEEFPERPDQPECSQYLKTGDCKYKFTCKYHHPKNRLPKQPPYALNDKGLPLRPDQDICTHYSRYGICKFGPACSFDHSVQPSYSTGSSQAVVEPPQVGANGNESDGWN',
 'KFK27286.1 Arabis alpina|AP2|AP2 family protein': 'MKNNNNNKSSSSSSYDSSLSPSSSSSSHQNWLSFSLSNNTSSNPNLTSSTSDHHHPHLSLFQAFSTSPVQRQDESPGVATGDAMAVLYNYPGGPKLENFLGGGATTTTTTRPMQQVQSLHGGVLSSDLQPPHPPPPSAAEIYDYELKSIAASFLGNYSGGHSSEVSSGHKQQDNTSVVSEVSPTPKKNVESFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQSRKGRQGGYDKEEKAARAYDLAALKYWGPTTTTNFPISNYESELEEMKHMTRQEFVASLRRKSSGFSRGASMYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTQEEAAEAYDIAAIKFRGLNAVTNFDISRYDVKSIATCNLPVGGLMPKQSPATAAADKAIDPSPSDPLPLTTSSLTFNVATPVHDQGRTFFHTGIPIKPDPADHYWSNVFGFQANPKAEIRPMATFGSDLHNPSPGFAIMPVMQDGENNFGGGFVGSEGYTNHSAASSAVTAIPLSSTTTIGNGNEGYVGNINWINNNISNSYQNPKANLSVMQTPVFGLE',
 'KFK29897.1 Arabis alpina|ERF|ERF family protein': 'MADSSDKEKKGTKREAVYHGVRMRSWGKWVSEIREPRKKSRIWLGTFPTAEMAMRAHDVAAMSIKGTSAILNFPELSDFLPRPISLNPRDVRAAAIKAAHMEFDTTAITSETETTSETTTFNESSETVSSSFSVTSIEENAVSEDLDEIVELPSLGTSLNESNEFVFFDSLEDLVFMPSWLRGGDEDFTTSLYNDDSPLSSVFEESFSWKHFP',
 'KFK36945.1 Arabis alpina|WRKY|WRKY family protein': 'MSMIFHGFKLVKELESNLPEKRPESLSVSLDEIAKTFDDANERLKIALGIKNSETVLNQSKPVMIASGSDQMLMHIEPGLMQEYWSRCGGFPSAQGTEAMVQRQLMAVDGGGGRNLTVVEGSSGAGSGSSTPKKGRRKDEGEEKTVFLVAALRTGNTDLPPDDNHTWRKYGQKEILGSRFPRAYYRCTHQKLYNCPAKKQVQRLNDDPFTFRVIYRGSHTCHIYSTAPTASAAAQTVPISSAVTTTGHTVDYAPALLDMADAMFGSSGIGSNMDFIFPSNDSSQHHHQ',
 'KFK36740.1 Arabis alpina|WRKY|WRKY family protein': 'MAASSFLTMDNSRTRQDMTSSGSANWSQGRTTTSLEGLEIPKFRSFAPSSISISPSLVSPSTCFSPSLFLDSPAFVSSSANILASPTTGALITNESNQKSINEEEKKKNNNNNFNFFDFSFQTQPSLVSAPTTTTTTTNSSIFQEQKKNESNQWNQTETRVNNQAISYNGREQRKGEDGYNWRKYGQKQVKGSENPRSYYKCTFPSCPTKKKVERSLEGQITEIVYKGSHNHPKPQSTRRSSSSSSYQSAVFNAGYDQSDQQNSNNNNSFHQSDSFAVEDNTTSGSVGDDEFERSSVVSREEEDCGSEPEAKRWKGENETNGGNGNASKTTREPRIVVQTTSDIDILDDGYRWRKYGQKVVKGNPNPRSYYKCTTIGCPVRKHVERASHDMRAVITTYEGKHNHDVPAARGSGYAINRPPQDSAAVPIRPAAISGHSNYTTSSQAPYTLQMLQNNTNSGPFGYAMNNNNVQSQQNFGGGGFSRAKEEPNEETSFFDSFLS',
 'KFK35572.1 Arabis alpina|WRKY|WRKY family protein': 'MVESGGEGNATTMIPDNGLTHHEPVNADLPPPSQEGHVDIPTEESVNIPSHQSHVEPLDAPIVPSLESEVVDHANSTNIISIDEESDEREDDDKDKDEDYYEEEEVEDNGEDEDEELEVEKDEDMVAKQDVVQPPSPKRRRYETPTNMIGSIRTSKQQRVIIQMESDEDLPDDGFRWRKYGQKVVKGNPNPRSPSSVDMTPPFTSLAPPMDMTQLYMTGLSMLPSLPVNNQNTSFMYQNDAPRMDASPNDMGVYKGIMDRLFVGIAEEILKRLDLENLCSVACVSTTLRSAVVSGVLPSLTSLDLSVFSPEEETLNHVLRGCIGVKSLTLNCLRLNSVAVCGVLGSHLQELHLLRCSLLNSSVLTSIGSLCPNLRVLTLEMADLDSPIVFQSNLTQLLNGCPYLESLQLNIRGILVDATAFQSIRFSLPETLKVLRLQPLLESEAILLMNRFKVTGSYLSTALSPSPSFTLQSLSLVLDLISDRLIIAITGSLPLLVKLDLEDRPEKEPYPDSDLTYTGLQSLGYCQQLTSLSLVRTCYNRKISFKRINDMGIFLLSEACKGLESVRLGGFPKVSDAGFASLLHSCRNLKKFEVRGAFLLSDLAFHDVTGSSCSLQEVRLSTCPLITSEAVKKLVLCSNLELLDLGSCKSISDSCLNSVSALRKLTSLNLAGADVTDTGMLALGKSNVPITQLSLRGCKRVSDRGILYLLSNEGTISRTLSTLDLGHMPGISDRAIHAITRYCKALTELSIRSCFHVTDSSIESLATRERQAEGGGKQLRKLNVHNCVSLTTGALRWLSKPSFAGLHWLGVGQTRFAGRKESVTATICEQRPWLTLCFDGCELGCYDGWEFHTPQRH',
 'KFK26712.1 Arabis alpina|NAC|NAC family protein': 'MNGRSMRLPPGFRFDPDDEDLVFEYLAKKVLHRPMDFDLPELRSCNVDPWDLLGEKNKEVYFFVKKEDRERKGIETLSGYWEKSEEEEVMEAGDRSYNECIHLEGRRKTFAFYIGKRPRGTITPWIMYEFRLLSSRATRWPSSSLSQKGELGKWRAVKVVVMEENEEEIEADEHASDESDGEEVVQAGD',
 'KFK25943.1 Arabis alpina|MYB_related|MYB_related family protein': 'MASANVQVTKAPSRNRVEETEDKQIQFNEQVSGENDYAPKVRKPYTITKERERWTDEEHKKFVEALKLYGRAWRRIEEHVGTKTAVQIRSHAQKFFSKVAREVTGGNGSSLEPIVIPPPRPKRKPMHPYPRKFGNEADQTSRSVSPSERDNRSPTSVLSTVGSEALGSSDSHSPNRSVSPVSSASPPTATTATAPEELESLKLELFPRERLLSRESLIKEPTKQSLKLFGKTVMVSDSDMSSSLTTSTYCKSPIQPLPRKLSQAETFPITINSQEELMSSWIQVPHKQDEVDSEKALQNEGSSTGSNTGSVDDTGHTDKISEAETMVCKWEFKPSERSAFSELRRRNSDSNSIGFGPYKKRKMVIEQEEEEQEIRLYL',
 'KFK39991.1 Arabis alpina|ERF|ERF family protein': 'MCGGAIISDFISSLSKSSFAEIELESNPSQLGHKRKTISVGRQKDEIDKKPKRQRKNLYRGIRQRPWGKWAAEIRDPRKGVRVWLGTFKTAEEAARAYDVEAIKIRGQKAKLNFPNQDTNLTRNGLEAKVDNDVSNDACVYESLSEDVMALEDYMRFYQIPYFDNDSVPQVSIIGNLWSF',
 'KFK27825.1 Arabis alpina|ERF|ERF family protein': 'MIASKNSSQETKGEKTKPVQDSGKHPVYRGVRKRNWGKWVSEIREPRKKSRIWLGTFPSPEMAARAHDVAALSIKGASAILNFPDLAGSFPRPNSLSPRDIQAAALKAAHMESPSSSSSSFTFSSSHSSSSLESLVSSSRTESEELGEIVKLPSLGSSYDGTTQLGNEFIFSDPVDFWDYEMIPSFSEGLLSRDWDLQGLYNYY',
 'KFK22396.1 Arabis alpina|bHLH|bHLH family protein': 'MSLYSHTTKSTFLLHCVTSRSLLCHHGFTSTCNFFFVISSMINQTCSFSLNQFLNILFWFLVLCFMQLEQGMRPILRCYNPTMCSTTMGRNFFTGATTSDKLFSRSFLTVKLKMKTESKEVAAKKHSDAERRRRLRINSQFATLRTILPNLVKQDKASVLGETVRNFNELKKMVKEIPTTPALEDSLRLGHCNNRDMTRVVFSCSDREGLMTELSESMKTVNAKAVRAEIMTVGGRSKCALFIQGVNGNEGLIRLKKSLKHVVNGKSSAAKNNNNNGGSLLTKQ',
 'KFK44896.1 Arabis alpina|bHLH|bHLH family protein': 'MIREECTPSSSWWEDVQHHHNDHANSLSSTSFYQKNSNGNNHNHANANANASSEVEDNLSISTLNASHRLDLTAESSNHHSLSARNQPTSSSDELLRDHVVSSHNHLWSLAFLPGGRSIGDQMMNQHHITSSRNSSTTSELPFEPPCDNGNGWIYDTNQVRYDQNSEQRLSKLSDLVGKHWSIAPPNNLDINHNINLHHHQHNHFEQDSQTNDDVSMYRQAMEVKNEEDLCYNNGLSGGGSLFQDPIESSTSFLDIRLSRPLSDINPSFKPCFKASNLSEFNKKEHQTASLASVRLGTTNAGKKKRCEENSDEVSKKAKCGGGSISPEKELPKAKLRDKITTLQQIVSPFGKTDTASVLQEAITYINFYQEQVKLLSTPYMKNSSIKDPWGGWEREDHNKRGAKHLDLKTRGLCLVPISYTPVAYRDNSATDYWSPSYRGSLYR',
 'KFK36333.1 Arabis alpina|GeBP|GeBP family protein': 'MAPLEDPPGDSSSDEGETESVEEEEANDVIEISSDSESSDSESETETDTVVVQPSVVSSSRRTKQPRVEETSTRMQTKRAKTDDEKKPYSQMLIEEDEIVILQGAIDFKLDKGKSFYQDQNEFYDFVKRSLNIDLSPHQLTEKVRSLNMKYIKGVEPTFLDAHDQKCFELAKVIDGLALELEKSEKIYEEDWFDKSYLVRAIASFGVSEDLVKQRWSMVAMETKKIIEDKWRELQAKEIEFMMLKTNFLCEVTSAMAKTLNP',
 'KFK35915.1 Arabis alpina|RAV|RAV family protein': 'MNATAETSNSSNDSSLPHKKRKRPLDDAPDNNALVKFKGVVHQKNGNWGAQIYTEQRRYWLGTFKTVADAAFAYDSASIKLRDFDANSPRNFPWNDLTVHEPAFQAGHTRDEVLNMIKDGSYQHKLREHIRARSHQKVPSDNNIARSKQSQGDKKSDKCFACKELFRKDLTPSDVGKLNRLVIHKKHAVTYLPFINDYQKEREEGEKGGDVDDVEVVFYDRDLRQWKFRYCYWRSSQSFVFTRGWNGFVKEKNLKEKDVVVFSTCEFPSNVETLEGQSKSFLMIDVRCFSENGFVAHEEIYVEHQRIWLGTFKSAADAAKAYDSTSIKVRGFDPNGHRNFPWDDFTVHEPAFQATKTRDEVLNMIKDGSYQHKFIEHLRNQSHKGASNNNVVGSKQREEGKESEKCFACKELFEKKLTPSDVGKLNRLVIPKKSAVKYLPFINDYQKEREDGEKGGDVDDVEVVFYDRALKQWKFRYCYWRSSQSFVFTRGWNGFVKEKNLKENDVVRFYTCEVPSNVEISEGQSKKFLMIDVHCFSENGFVAHEEVNKTVHNHNSFEKTENLFNSKLKVEETKSEEKKGGFMLFGVRIQ',
 'KFK31098.1 Arabis alpina|C3H|C3H family protein': 'MTETQQLQNSTGSIPSSEKIEDTFRRMKVNEENMEQSSPTYPDRPGERDCQFFLRTGLCGYGNTCRYNHPPTHLPHGVIYHRDELPERIGQPDCEYFLKTGACKYGATCKYHHPKDRNGAGPVLFNVLGYPMRMGEKACPYYMHTGSCRFGVACKFHHPHPNNTQPLNGHSTYAGGYPSVGYPYGGGLPMMSLPPATYGAMSRPQVPQPQAYMPYMVAPSQGLCLPPQAWAPYMGASNPIYNMKTQPDSSSSASVPVAVTSHYHQDFSERAECRFFMNTGTCKYGDDCKYIHPKERMLQSPPPNLLNPILLPARPGQPACGNFKAYGVCKFGANCKFDHSMPPNSYYNTGLTMVSLPNTTTAYAPPVSTHLRISSPPSSSDSVTISNGKPAAETEKQDDSPAQPDKSDVEDSSPPNHSDSTTLTNGKPDAENPISETKKPDDNTAKPDSSEVQDTPENSS',
 'KFK37092.1 Arabis alpina|LBD|LBD family protein': 'MASSGNGTTAGTGSPCGACKFLRRKCASDCIFAPYFSSEQGASRFAAIHKVFGASNVSKLLLNVPIHDRCEAVVTIAYEAQARLHDPVYGCVSHIFALQQQVAYLQAQVIQMKAQIAGHHTSAAGDLGNSSESTHQFMTWQQNNGSPIGTAYSTPYNQQHSYYGHVNPNNPVSPQSSLEESFSNTSSDVTTTTNVRETHQNGEDVYGQGGLGFHEGYPNKKRSVSYCNGDLGELQALALRMMKN',
 'KFK34259.1 Arabis alpina|C2H2|C2H2 family protein': 'MALDTLNSPTSTTTAPPPFLTESENLESWTKRKRTKRHRTDHQHQSNPPSEEEYLALCLLMLARGSDDDHSPPPPSDHHHHRDYKCSVCGRSFPSYQALGGHKTSHRKPVSNNINNNNEDQSTNDHNGPVTNNGNISNVLVGQSGKTHKCSICFKSFPSGQALGGHKRCHYDGGNANGNSNGNNNHGFDLNLPADQVMEDFNDEAFGKSQLSGEETKSPV',

In [30]:
len(plant_TF_dict)

310656

In [41]:
plant_TF_df = pd.DataFrame.from_dict(plant_TF_dict, orient='index').reset_index()
plant_TF_df["species"] = plant_TF_df["index"].str.extract(r'^[^\s]+\s+([A-Z][a-z]+ [a-z]+)')
plant_TF_df

,index,0,species
0,KFK36254.1 Arabis alpina|G2-like|G2-like famil...,MYSAIRSLPVDGSMGEYSDGTNLPIEACLVLTTDPKPRLRWTTELH...,Arabis alpina
1,KFK25038.1 Arabis alpina|GeBP|GeBP family protein,MAPKHTDTIQNPPMPSSSSEEESASSGEDSDSSKKHNSASDSDPIK...,Arabis alpina
2,KFK35037.1 Arabis alpina|bZIP|bZIP family protein,MTTTTTPHWPDFSSQKLPSIAATAAATAATAGQNQQNQNPSWMDEF...,Arabis alpina
3,KFK44643.1 Arabis alpina|ERF|ERF family protein,MEGERHDSTTSSSRKRSHEPAEERPASHVATMAFKEKPYRGIRMRK...,Arabis alpina
4,KFK32619.1 Arabis alpina|B3|B3 family protein,MAKPPQFFHTLVNTHLVIPKDFFSKYIQGKSVDDTVELKSDSTDIN...,Arabis alpina
...,...,...,...
310651,Zpz_sc00227.1.g00450.1.am.mk Zoysia pacifica|b...,MYGSTVSKDLNLPAVQPQPATGARTPPPQMSSSGLLRYRSAPSNLL...,Zoysia pacifica
310652,Zpz_sc01778.1.g00020.1.am.mk Zoysia pacifica|M...,MARKPNQHAAAGTGAAAEEKKERRGLWSPEEDERLFTQITCHGVST...,Zoysia pacifica
310653,Zpz_sc01095.1.g00030.1.sm.mk Zoysia pacifica|H...,MEGSQSRSGGGSSSPPPFLIKTYEMVEDPATNRVVSWGPGGASFVV...,Zoysia pacifica
310654,Zpz_sc05215.1.g00010.1.am.mk Zoysia pacifica|b...,MSDDSDKQRQCRRGVGVHELDAAMALADLAGVSPEPQKLHLQPAAA...,Zoysia pacifica
310655,Zpz_sc00243.1.g00020.1.sm.mkhc Zoysia pacifica...,MDADFFADIDFAALLASFSDEPAAVSDLIVPSPPPSSPPPARDGES...,Zoysia pacifica

In [ ]:
# How many sequences per species?
plant_TF_df["species"].value_counts()

species
Glycine max                       6150
Brassica napus                    5984
Panicum virgatum                  5702
Camelina sativa                   5266
Nicotiana tabacum                 5103
                                  ...
Dunaliella salina                  111
Ostreococcus sp                    102
Picochlorum sp                     101
Auxenochlorella protothecoides      99
Ostreococcus tauri                  93
Name: count, Length: 164, dtype: int64

In [45]:
plant_TF_df.dropna()[plant_TF_df.dropna()["species"].str.contains("Arabidopsis thaliana")]

,index,0,species
20770,AT4G29930.1 Arabidopsis thaliana|bHLH|bHLH fam...,MEDLDHEYKNYWETTMFFQNQELEFDSWPMEEAFSGSGESSSPDGA...,Arabidopsis thaliana
20771,AT5G51780.1 Arabidopsis thaliana|bHLH|bHLH fam...,MEKMMHRETERQRRQEMASLYASLRSLLPLHFIKGKRSTSDQVNEA...,Arabidopsis thaliana
20772,AT3G55370.3 Arabidopsis thaliana|Dof|OBF-bindi...,MVFSSLPVNQFDSQNWQQMISILVFFSTSRLFKKLFLVDKNLFSCL...,Arabidopsis thaliana
20773,AT3G19500.1 Arabidopsis thaliana|bHLH|bHLH fam...,MGDTAEDQDDRAMMEAEGVTSFSELLMFSDGVLSSSSDHQPEGNVG...,Arabidopsis thaliana
20774,AT3G02380.1 Arabidopsis thaliana|CO-like|CONST...,MLKEESNESGTWARACDTCRSAACTVYCEADSAYLCTTCDARVHAA...,Arabidopsis thaliana
...,...,...,...
23061,AT4G35580.2 Arabidopsis thaliana|NAC|NAC trans...,MGAVSMESLPLGFRFRPTDEELVNHYLRLKINGRHSDVRVIPDIDV...,Arabidopsis thaliana
23062,AT2G18160.1 Arabidopsis thaliana|bZIP|basic le...,MASSSSTYRSSSSSDGGNNNPSDSVVTVDERKRKRMLSNRESARRS...,Arabidopsis thaliana
23063,AT2G24645.1 Arabidopsis thaliana|B3|B3 family ...,MANQHFFKPLLPGFHTHLRIPVAFFLKNIEGRYEQKTAELRSDASK...,Arabidopsis thaliana
23064,AT2G41070.3 Arabidopsis thaliana|bZIP|bZIP fam...,MGSIRGNIEEPISQSLTRQNSLYSLKLHEVQTHLGSSGKPLGSMNL...,Arabidopsis thaliana
23065,AT5G10510.3 Arabidopsis thaliana|AP2|AINTEGUME...,MMAPMTNWLTFSLSPMEMLRSSDQSQFVSYDASSAASSSPYLLDNF...,Arabidopsis thaliana

# Using Morrfy list + TAIR

In [ ]:
# Downloaded from TAIR
arabidopsis_domains = pd.read_csv("../data/all.domains.txt", sep = "\t", header = None)
arabidopsis_domains

,0,1,2,3,4,5,6,7,8,9,10
0,AT1G01010.1,.,Seg,seg,seg,319,331,Null,Null,Null,Null
1,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily
2,AT1G01010.1,.,Gene3D,2.170.150.80,NAC_domain_superfamily,12,160,Null,Null,IPR036093,NAC domain superfamily
3,AT1G01010.1,.,Prosite_profiles,PS51005,NAC_domain,3,156,Null,Null,IPR003441,NAC domain
4,AT1G01010.1,.,Pfam,PF02365,NAC_domain,5,137,Null,Null,IPR003441,NAC domain
...,...,...,...,...,...,...,...,...,...,...,...
627644,ATMG01410.1,.,alphafold,AF-P92567-F1,AF-P92567-F1,1,204,Null,Null,Null,Null
627645,ATMG01410.1,.,Pfam,PF05919,"RNA-dependent_RNA_polymerase,",7,164,Null,Null,IPR008686,"RNA-dependent RNA polymerase, mitoviral"
627646,ATMG01410.1,.,Seg,seg,seg,58,69,Null,Null,Null,Null
627647,ATMG01410.1,.,Seg,seg,seg,168,183,Null,Null,Null,Null
627648,ATMG01410.1,.,SuperFamily,SSF56672,DNA/RNA_polymerase_superfamily,28,166,Null,Null,IPR043502,DNA/RNA polymerase superfamily

In [ ]:
# Downloaded mapping from TAIR
AGI2uniprot = pd.read_csv("../data/AGI2uniprot.txt", sep = "\t", header = None)
AGI2uniprot

                  0             1
0       AT1G08910.1  A0A0A7EPL0-2
1       AT5G51560.1    A0A178UFM8
2       AT3G60460.1    A0A178VEK7
3       AT1G56060.2    A0A178WF56
4       AT3G50610.2    A0A1I9LMX5
...             ...           ...
108915  AT1G23870.1        W8QP88
108916  AT1G08990.1        W8QPB2
108917  AT1G07250.1        W8QPB7
108918  AT1G05560.1        W8QPC2
108919  AT1G02730.1        W8QPC8

[108920 rows x 2 columns]

In [ ]:
# merging
domains_with_uniprot = pd.merge(arabidopsis_domains, AGI2uniprot, on = 0)
domains_with_uniprot

,0,1_x,2,3,4,5,6,7,8,9,10,1_y
0,AT1G01010.1,.,Seg,seg,seg,319,331,Null,Null,Null,Null,Q0WV96
1,AT1G01010.1,.,Seg,seg,seg,319,331,Null,Null,Null,Null,A0A178WAE4
2,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
3,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,A0A178WAE4
4,AT1G01010.1,.,Gene3D,2.170.150.80,NAC_domain_superfamily,12,160,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
...,...,...,...,...,...,...,...,...,...,...,...,...
914758,ATMG01410.1,.,alphafold,AF-P92567-F1,AF-P92567-F1,1,204,Null,Null,Null,Null,P92567
914759,ATMG01410.1,.,Pfam,PF05919,"RNA-dependent_RNA_polymerase,",7,164,Null,Null,IPR008686,"RNA-dependent RNA polymerase, mitoviral",P92567
914760,ATMG01410.1,.,Seg,seg,seg,58,69,Null,Null,Null,Null,P92567
914761,ATMG01410.1,.,Seg,seg,seg,168,183,Null,Null,Null,Null,P92567
914762,ATMG01410.1,.,SuperFamily,SSF56672,DNA/RNA_polymerase_superfamily,28,166,Null,Null,IPR043502,DNA/RNA polymerase superfamily,P92567

In [ ]:
# Loading data from PADI where the fragments come from TFs
padi_s1 = pd.read_excel("../data/padi_s1_41586_2024_7707_MOESM2_ESM (1).xlsx")
padi_s1

,Sub Library,Fragment Name,Fragment Sequence,Gene Model,ATG Number,Start Position,PADI Score,TF Family,Mean Disorder,AD Subtype,...,CountN,CountP,CountQ,CountR,CountS,CountT,CountV,CountW,CountY,Aromatics
0,Lib1,AT1G01010.1_1,MEDQVGFGFRPNDEELVGHYLRNKIEGNTSRDVEVAISEV,AT1G01010.1,AT1G01010,1,1.004699,NAC,0.254442,1.0,...,3,1,1,3,2,1,5,0,1,5
1,Lib1,AT1G01010.1_11,PNDEELVGHYLRNKIEGNTSRDVEVAISEVNICSYDPWNL,AT1G01010.1,AT1G01010,11,0.575876,NAC,0.131235,NaN,...,5,2,0,2,3,1,4,1,2,6
2,Lib1,AT1G01010.1_21,LRNKIEGNTSRDVEVAISEVNICSYDPWNLRFQSKYKSRD,AT1G01010.1,AT1G01010,21,-0.300407,NAC,0.104265,NaN,...,4,1,1,4,5,1,3,1,2,6
3,Lib1,AT1G01010.1_31,RDVEVAISEVNICSYDPWNLRFQSKYKSRDAMWYFFSRRE,AT1G01010.1,AT1G01010,31,0.105372,NAC,0.105342,NaN,...,2,1,1,5,5,0,3,2,3,9
4,Lib1,AT1G01010.1_41,NICSYDPWNLRFQSKYKSRDAMWYFFSRRENNKGNRQSRT,AT1G01010.1,AT1G01010,41,-0.167147,NAC,0.240860,NaN,...,5,1,2,6,5,1,0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69568,Lib10,ATMG00940.1_91,SDFVVKAEDVEASMAIFWTPGTRVKMAMETEDSSRITWFQ,ATMG00940.1,ATMG00940,91,-0.139281,Other,0.084480,NaN,...,0,1,1,2,4,4,4,2,0,5
69569,Lib10,ATMG00940.1_101,EASMAIFWTPGTRVKMAMETEDSSRITWFQGIVFYTYQET,ATMG00940.1,ATMG00940,101,-0.064551,Other,0.104625,NaN,...,0,1,2,2,3,6,2,2,2,7
69570,Lib10,ATMG00940.1_111,GTRVKMAMETEDSSRITWFQGIVFYTYQETGPWRGSPWNS,ATMG00940.1,ATMG00940,111,-0.410777,Other,0.159452,NaN,...,1,2,2,3,4,5,2,3,2,7
69571,Lib10,ATMG00940.1_121,EDSSRITWFQGIVFYTYQETGPWRGSPWNSFRYKIPFTIP,ATMG00940.1,ATMG00940,121,0.329820,Other,0.204375,NaN,...,1,4,2,3,4,4,1,3,3,10
69572,Lib10,ATMG00940.1_124,RITWFQGIVFYTYQETGPWRGSPWNSFRYKIPFTIPLIFL,ATMG00940.1,ATMG00940,124,3.913026,Other,0.215280,6.0,...,1,4,2,3,2,4,1,3,3,13

In [ ]:
# Expected num of arabidopsis TFs
padi_s1["TF_uniprot"] = padi_s1["Fragment Name"].str.split("_").str[0]
arabidopsis_TF_uniprotIDs = padi_s1["TF_uniprot"].unique()
len(arabidopsis_TF_uniprotIDs)

1918

In [ ]:
arabidopsis_TF_domains = domains_with_uniprot[domains_with_uniprot[0].isin(arabidopsis_TF_uniprotIDs)]
arabidopsis_TF_domains

,0,1_x,2,3,4,5,6,7,8,9,10,1_y
0,AT1G01010.1,.,Seg,seg,seg,319,331,Null,Null,Null,Null,Q0WV96
1,AT1G01010.1,.,Seg,seg,seg,319,331,Null,Null,Null,Null,A0A178WAE4
2,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
3,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,A0A178WAE4
4,AT1G01010.1,.,Gene3D,2.170.150.80,NAC_domain_superfamily,12,160,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
...,...,...,...,...,...,...,...,...,...,...,...,...
912049,AT5G67580.1,.,Gene3D,1.10.10.60,1.10.10.60,2,58,Null,Null,Null,Null,Q9FJW5
914461,ATMG00940.1,.,alphafold,AF-P92530-F1,AF-P92530-F1,1,164,Null,Null,Null,Null,P92530
914462,ATMG00940.1,.,PANTHER,PTHR31384,Auxin_response_factor,4,151,Null,Null,IPR044835,Auxin response factor,P92530
914463,ATMG00940.1,.,Pfam,PF06507,Auxin_response_factor,70,151,Null,Null,IPR010525,Auxin response factor domain,P92530
914464,ATMG00940.1,.,Gene3D,2.30.30.1040,2.30.30.1040,108,154,Null,Null,Null,Null,P92530

In [22]:
arabidopsis_TF_domains = arabidopsis_TF_domains[arabidopsis_TF_domains[9] != "Null"]
arabidopsis_TF_domains

,0,1_x,2,3,4,5,6,7,8,9,10,1_y
2,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
3,AT1G01010.1,.,SuperFamily,SSF101941,NAC_domain_superfamily,5,156,Null,Null,IPR036093,NAC domain superfamily,A0A178WAE4
4,AT1G01010.1,.,Gene3D,2.170.150.80,NAC_domain_superfamily,12,160,Null,Null,IPR036093,NAC domain superfamily,Q0WV96
5,AT1G01010.1,.,Gene3D,2.170.150.80,NAC_domain_superfamily,12,160,Null,Null,IPR036093,NAC domain superfamily,A0A178WAE4
6,AT1G01010.1,.,Prosite_profiles,PS51005,NAC_domain,3,156,Null,Null,IPR003441,NAC domain,Q0WV96
...,...,...,...,...,...,...,...,...,...,...,...,...
912046,AT5G67580.1,.,Smart,SM00526,"Linker_histone_H1/H5,",119,184,Null,Null,IPR005818,"Linker histone H1/H5, domain H15",Q9FJW5
912047,AT5G67580.1,.,Smart,SM00717,SANT/Myb_domain,4,59,Null,Null,IPR001005,SANT/Myb domain,Q9FJW5
912048,AT5G67580.1,.,Gene3D,1.10.10.10,Winged_helix-like_DNA-binding,118,202,Null,Null,IPR036388,Winged helix-like DNA-binding domain superfamily,Q9FJW5
914462,ATMG00940.1,.,PANTHER,PTHR31384,Auxin_response_factor,4,151,Null,Null,IPR044835,Auxin response factor,P92530
914463,ATMG00940.1,.,Pfam,PF06507,Auxin_response_factor,70,151,Null,Null,IPR010525,Auxin response factor domain,P92530

In [25]:
arabidopsis_TF_domains[10].value_counts()[:20]

10
SANT/Myb domain                                    2324
AP2/ERF domain                                     1496
Zinc finger C2H2-type                               943
Transcription factor, MADS-box                      921
B3 DNA binding domain                               773
Myc-type, basic helix-loop-helix (bHLH) domain      637
Homeobox-like domain superfamily                    631
Myb domain                                          605
Zinc finger, CCCH-type                              570
Homeobox domain                                     567
WRKY domain                                         516
Basic-leucine zipper domain                         464
Helix-loop-helix DNA-binding domain superfamily     430
DNA-binding pseudobarrel domain superfamily         415
NAC domain superfamily                              370
NAC domain                                          368
WRKY domain superfamily                             344
Transcription factor, MADS-box superfamily          326
Zinc finger, GATA-type                              296
Myb domain, plants                                  274
Name: count, dtype: int64